<?php
$data = $block->add();
?>
<h1>Edit room id:<?= $data['product_id'];?></h1>
<form action="http://nhlmg.com/cybergame/customer/update/" method="POST">
    <input type="hidden" value="<?= $data['product_id']; ?>" name="product_id" />
    <label>Name</label>
    <input type="text" value="<?= $data['room_name'] ?>" name="room_name" readonly />
    <label>Price</label>
    <input type="number" value="<?= $data['food_price'] + $data['drink_price']; ?>" name="price" readonly />
    <label>Number pc</label>
    <input type="number" name="number_pc" value="<?= $data['number_pc']; ?>" required/>
    <label>Address</label>
    <input type="text" name="address" value="<?= $data['address']; ?>" required/>
    <label>Food price</label>
    <input type="number" name="food_price" value="<?= $data['food_price']; ?>" required/>
    <label>Drink price</label>
    <input type="number" name="drink_price" value="<?= $data['drink_price']; ?>" required/>
    <input type="submit" value="submit" name="submit"/>
</form>


